# -*- coding: utf-8 -*-
from setuptools import setup

package_dir = \
{'': 'python'}

packages = \
['lvmscp', 'lvmscp.actor', 'lvmscp.actor.commands']

package_data = \
{'': ['*'], 'lvmscp': ['etc/*']}

install_requires = \
['astropy>=4.2.1,<5.0.0',
 'black>=21.7b0,<22.0',
 'click-default-group>=1.2.2,<2.0.0',
 'click>=8.0.0,<9.0.0',
 'daemonocle>=1.2.3,<2.0.0',
 'sdss-access>=0.2.3',
 'sdss-clu>=1.0.0,<2.0.0',
 'sdss-cluplus>=0.0.14,<0.0.15',
 'sdss-tree>=2.15.2',
 'sdsstools>=0.4.0',
 'setuptools>=62.1.0,<63.0.0',
 'sphinx-click>=3.0.1,<4.0.0']

extras_require = \
{'docs': ['Sphinx>=3.0.0,<4.0.0', 'sphinx_bootstrap_theme>=0.4.12']}

entry_points = \
{'console_scripts': ['lvmscp = lvmscp.__main__:lvmscp']}

setup_kwargs = {
    'name': 'sdss-lvmscp',
    'version': '0.1.3',
    'description': 'Simple Template package for creating SDSS Python projects',
    'long_description': '# lvmscp\n\n![Versions](https://img.shields.io/badge/python->3.8-blue)\n[![Code style: black](https://img.shields.io/badge/code%20style-black-000000.svg)](https://github.com/psf/black)\n[![Documentation Status](https://readthedocs.org/projects/lvmscp/badge/?version=latest)](https://lvmscp.readthedocs.io/en/latest/?badge=latest)\n[![Test](https://github.com/sdss/lvmscp/actions/workflows/test.yml/badge.svg)](https://github.com/sdss/lvmscp/actions/workflows/test.yml)\n[![Docker](https://github.com/sdss/lvmscp/actions/workflows/Docker.yml/badge.svg)](https://github.com/sdss/lvmscp/actions/workflows/Docker.yml)\n[![codecov]](https://codecov.io/gh/sdss/lvmscp)\n\nSDSS-V LVM(Local Volume Mapper) control software for the whole Spectrograpgh system\n\n## Quick Start\n\n### Prerequisite\n\nInstall [CLU](https://clu.readthedocs.io/en/latest/) by using PyPI.\n```\n$ pip install sdss-clu\n```\n\nInstall [RabbitMQ](https://www.rabbitmq.com/) by using apt-get.\n\n```\n$ sudo apt-get install -y erlang\n$ sudo apt-get install -y rabbitmq-server\n$ sudo systemctl enable rabbitmq-server\n$ sudo systemctl start rabbitmq-server\n```\n\nInstall [pyenv](https://github.com/pyenv/pyenv) by using [pyenv installer](https://github.com/pyenv/pyenv-installer).\n\n```\n$ curl https://pyenv.run | bash\n```\n\nYou should add the code below to `~/.bashrc` by using your preferred editor.\n```\n# pyenv\nexport PYENV_ROOT="$HOME/.pyenv"\nexport PATH="$PYENV_ROOT/bin:$PATH"\neval "$(pyenv init -)"\neval "$(pyenv init --path)"\neval "$(pyenv virtualenv-init -)"\n```\n\n### Ping-pong test\n\nClone this repository.\n```\n$ git clone https://github.com/sdss/lvmscp\n$ cd lvmscp\n```\n\nSet the python 3.9.1 virtual environment.\n```\n$ pyenv install 3.9.1\n$ pyenv virtualenv 3.9.1 lvmscp-with-3.9.1\n$ pyenv local lvmscp-with-3.9.1\n```\n\nInstall [poetry](https://python-poetry.org/) and dependencies. For more information, check [sdss/archon](https://github.com/sdss/archon).\n```\n$ pip install poetry\n$ python create_setup.py\n$ pip install -e .\n```\n\nStart `lvmscp` actor inside your virtualenv directory.\n```\n$ lvmscp start\n```\n\nIn another terminal, type `clu` and `lvmscp ping` for test.\n```\n$ clu\nlvmscp ping\n07:41:22.636 lvmscp > \n07:41:22.645 lvmscp : {\n    "text": "Pong."\n}\n```\n\nStop `lvmscp` actor.\n```\n$ lvmscp stop\n```\n',
    'author': 'Changgon Kim',
    'author_email': 'changgonkim@khu.ac.kr',
    'maintainer': None,
    'maintainer_email': None,
    'url': 'https://github.com/sdss/lvmscp',
    'package_dir': package_dir,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'extras_require': extras_require,
    'entry_points': entry_points,
    'python_requires': '>=3.8,<3.10',
}
from build import *
build(setup_kwargs)

setup(**setup_kwargs)

# This setup.py was autogenerated using poetry.
