# -*- coding: utf-8 -*-
from setuptools import setup

package_dir = \
{'': 'python'}

packages = \
['lvmscp', 'lvmscp.actor', 'lvmscp.actor.commands']

package_data = \
{'': ['*'], 'lvmscp': ['etc/*']}

install_requires = \
['astropy>=4.2.1,<5.0.0',
 'click-default-group>=1.2.2,<2.0.0',
 'click>=8.0.0,<9.0.0',
 'daemonocle>=1.2.3,<2.0.0',
 'sdss-access>=0.2.3',
 'sdss-clu>=1.0.0,<2.0.0',
 'sdss-tree>=2.15.2',
 'sdsstools>=0.4.0']

extras_require = \
{'docs': ['Sphinx>=3.0.0,<4.0.0', 'sphinx_bootstrap_theme>=0.4.12']}

entry_points = \
{'console_scripts': ['lvmscp = lvmscp.__main__:lvmscp']}

setup_kwargs = {
    'name': 'sdss-lvmscp',
    'version': '0.1.0a0',
    'description': 'Simple Template package for creating SDSS Python projects',
    'long_description': '# SCP\n\n![Versions](https://img.shields.io/badge/python->3.7-blue)\n[![Documentation Status](https://readthedocs.org/projects/sdss-lvmscp/badge/?version=latest)](https://sdss-lvmscp.readthedocs.io/en/latest/?badge=latest)\n[![Travis (.org)](https://img.shields.io/travis/sdss/lvmscp)](https://travis-ci.org/sdss/lvmscp)\n[![codecov](https://codecov.io/gh/sdss/lvmscp/branch/main/graph/badge.svg)](https://codecov.io/gh/sdss/lvmscp)\n\nSimple Template package for creating SDSS Python projects\n',
    'author': 'Changgon Kim',
    'author_email': 'changgonkim@khu.ac.kr',
    'maintainer': None,
    'maintainer_email': None,
    'url': 'https://github.com/sdss/lvmscp',
    'package_dir': package_dir,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'extras_require': extras_require,
    'entry_points': entry_points,
    'python_requires': '>=3.7,<4.0',
}
from build import *
build(setup_kwargs)

setup(**setup_kwargs)

# This setup.py was autogenerated using poetry.
